import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./navbar/Navbar";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"
          strategy="beforeInteractive"
        />
        <Script
          // @ts-expect-error
          nowprocket nitro-exclude type="text/javascript" id="sa-dynamic-optimization" data-uuid="4bc597c7-a6c1-46b0-978e-b31458da6e8a" src="/script.js"
          strategy="beforeInteractive"
        />
      </head>
      <body style={{ backgroundColor: '#4A90E2' }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
